# Landscape of accounting in the R universe


## Introduction
Why R for accounting: other tools based on problems to solve
Data skills for new generation of accountants - coding is dreaded but working with data is appreciated

What’s on the plate or.. better huge black hole

## Background
From bookkeeping to excel to r

## Method
Data collection - cran and github ( package in development)
Alignment with accounting tasks

## Results and discussion
Themes/ topics
Alignment with current developments
Priority areas for developments - current gaps and push to automate

How to get accountants on board - use, training, further development

## Conclusion


Felix: 

list of packages which you think we need to include in the paper

Maria: same

next time: alignmentwith accounting tasks - classification/themes


classification:

1. Reporting and communication:
RShiny/ flexdashboard / Rmarkdown

2. external records access
XBRL / finstr

https://cran.r-project.org/web/packages/XBRL/index.html
https://github.com/bergant/finstr


Tidy Accounting!!!!! - new package? new paper!

1. external records access
XBRL
finstr
finreportr

2. data tables
knitr
kableExtra
flextable
htmlTable
htmlwidgets
DT
xlsx
roomba

3. data management
skimr
dplyr
tidyverse
lubridate
fAssets
FinancialInstrument

4. Reporting and communication:
RShiny
PerformanceAnalytics
quantmod
portfolio
flexdashboard
Rmarkdown
ggplot2
waterfalls
plotly
